### ISSUE TITLE
NCL examples

### ISSUE THREAD

**Issue by jukent** [NCAR/notebook-gallery#21]
Check with John Clyne.
Which examples have the most hits?
Work on this in a hackathon with the NCL team?

**Comment by bonnland** [comment]
@kmpaul Do I recall that John provided the results to you?   If so, could you make John's results available, perhaps in this issue?

**Comment by kmpaul** [comment]
@bonnland Here is a [Google Sheets version](https://docs.google.com/spreadsheets/d/10jNL8PRBVYsiGTUoeeQ2u67Fd0l2CUHnAxZxslJkMGY/edit?usp=sharing) of the Excel spreadsheet with the NCL examples sorted by numbers of visits on the NCL gallery website.  It's not the same as website "click statistics," which is why I haven't shared it, yet.  I keep meaning to add to this spreadsheet the link to the web page with the example shown, but I haven't had time to do it.  Here's the caveat mentioned by John Clyne:

> Kevin, I’ve attached a spreadsheet. The data I have is based on the script name. Unfortunately, it takes a little bit of effort to match the script name, e.g.  xy_2.ncl, to the web page on the NCL site that contains the gallery image. They are all rooted under [https://www.ncl.ucar.edu/Applications/](https://www.ncl.ucar.edu/Applications/).
>
>cheers - jc

Now, I think we need to be careful _not_ to do examples that a summer intern would find fun, educational, or rewarding to do themselves.  In that vein, I think we need to go through these NCL examples and do some triage.  We should label each NCL example as either:

1. Good for an intern
2. Good for us to translate
3. Wait to translate

Also, there is this page ([https://www.ncl.ucar.edu/Applications/NCL_to_Python/](https://www.ncl.ucar.edu/Applications/NCL_to_Python/)) on the NCL Gallery website that shows that some Python translations have already been done/started.

**Comment by kmpaul** [comment]
Actually, considering the https://www.ncl.ucar.edu/Applications/NCL_to_Python/ web page already exists, I am wondering if these examples make sense in the NCAR/notebook-gallery repo.  We should discuss.

**Comment by jukent** [comment]
What is the key difference between views and click statistics? Is one more indicative than the other of what examples should be used?

I like the labeling idea. I am not sure what would make one plot more fun/educational/rewarding than the next - but I hope it is clear as we look through the NCL plots and discuss.

**Comment by kmpaul** [comment]
John Clyne has already starting making the connection between web pages and NCL example scripts:

https://docs.google.com/spreadsheets/d/13GwtCuM2KIo1TZOOBJhC1RlQHKRdZVU7iIqx6JqskaA/edit?usp=sharing

This is John's identified examples to start translating to Python.

**Comment by jukent** [comment]
This is now in its own repo:
https://github.com/NCAR/GeoCAT-examples/issues

**Comment by kmpaul** [comment]
Closing, as this has moved to the new repo.
