### ISSUE TITLE
Allow Users to assign chunking in calc_ocean_heat

### ISSUE THREAD

**Issue by jukent** [NCAR/notebook-gallery#3]
This is in reference to OHC.py #2 

Currently the chunking is done within the calc_ocean_heat function instead of in a separate read files. The chunking dimension is set to lev, since that is the only dimension guaranteed to exist in the opened file. I am wary of having a string as a function argument, and am not sure how else to allow the user to pick the dimensions.

**Comment by andersy005** [comment]
In https://github.com/NCAR/notebook-gallery/blob/master/OHC.py#L4, the user is asked to supply a filename/filepath, would it be useful to change
```python
def calc_ocean_heat(file,dlim=275):
```

to 
```python
def calc_ocean_heat(ds, dlim=275):
```

where `ds`: is an xarray dataset?

I am envisioning cases where you might have to deal with multiple files instead of just one file. Having `ds` as an argument in place of `file` would make `calc_ocean_heat()` robust. As a (good) side effect, the chucking issue would be handled outside of `calc_ocean_heat()`

**Comment by jukent** [comment]
I added a read file function read_thetao_nc which reads in a potential temperature nc function, but I still want to make that read function flexible to user-defined chunking:

def read_thetao_nc(file):
    ds = xr.open_dataset(file,chunks={'lev':1})
    return ds

I do not know the best practive for having the dimension (here 'lev') as an argument.
